insert into tb_categoria (Nome, Tipo) values ("Salario", "Receita");
insert into tb_categoria (Nome, Tipo) values ("Dividendos", "Receita");
insert into tb_categoria (Nome, Tipo) values ("Alugueis", "Receita");
insert into tb_categoria (Nome, Tipo) values ("Refeicao", "Despesa");
insert into tb_categoria (Nome, Tipo) values ("Onibus", "Despesa");
insert into tb_categoria (Nome, Tipo) values ("Saude", "Despesa");
insert into tb_categoria (Nome, Tipo) values ("Mercado", "Despesa");
insert into tb_categoria (Nome, Tipo) values ("Gasolina", "Despesa");
insert into tb_categoria (Nome, Tipo) values ("Lanche", "Despesa");
insert into tb_categoria (Nome, Tipo) values ("Cigarro", "Despesa");
insert into tb_categoria (Nome, Tipo) values ("Happy Hour", "Despesa");
insert into tb_movimentacao(dataHora, idCategoria, valor, CategoriaId) values ("2019-10-05 10:00:00", 1, 9000.0, 1);
insert into tb_movimentacao(dataHora, idCategoria, valor, CategoriaId) values ("2019-10-05 10:00:00", 2, 6052.99, 2);
insert into tb_movimentacao(dataHora, idCategoria, valor, CategoriaId) values ("2019-10-05 10:00:00", 3, 2500.0, 3);
insert into tb_movimentacao(dataHora, idCategoria, valor, CategoriaId) values ("2019-10-05 08:00:00", 5, 4.7, 5);
insert into tb_movimentacao(dataHora, idCategoria, valor, CategoriaId) values ("2019-10-05 15:00:00", 4, 55.5, 4);
insert into tb_movimentacao(dataHora, idCategoria, valor, CategoriaId) values ("2019-10-05 21:00:00", 11, 90.36, 11);
insert into tb_movimentacao(dataHora, idCategoria, valor, CategoriaId) values ("2019-10-06 02:00:00", 5, 4.7, 5);
insert into tb_movimentacao(dataHora, idCategoria, valor, CategoriaId) values ("2019-10-06 14:00:00", 8, 200, 8);
insert into tb_movimentacao(dataHora, idCategoria, valor, CategoriaId) values ("2019-10-06 23:00:00", 4, 150.5, 4);